name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: julia-actions/setup-julia@latest
    - run: |
        println("Hello, World!")
        using InteractiveUtils; versioninfo()
        using Pkg; Pkg.add(PackageSpec(url="https://github.com/JuliaComputing/MKL.jl"));
      shell: bash -c "julia --color=yes --project {0}"
